# Generated by Django 4.2.5 on 2023-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=14)),
                ('nickname', models.TextField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
