# Generated by Django 4.2.5 on 2023-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activities_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('activities_name', models.TextField()),
                ('activities_desc', models.TextField()),
                ('activities_price', models.FloatField()),
                ('activities_rating', models.IntegerField()),
            ],
        ),
    ]
