# Generated by Django 4.2.5 on 2023-10-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceStay',
            fields=[
                ('place_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('place_name', models.TextField()),
                ('place_type', models.TextField()),
                ('place_desc', models.TextField()),
                ('place_rating', models.IntegerField()),
            ],
        ),
    ]
