# Generated by Django 4.2.5 on 2023-10-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_placestay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('location_name', models.TextField()),
                ('location_desc', models.TextField()),
                ('activities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.activities')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.signup')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.placestay')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.restaurant')),
            ],
        ),
    ]
